import re

with open("main.tex", "r") as f:
    text = f.read()

# Remove the Broader Impact subsection completely to save space
broader_impact_regex = r"(\\subsection\{Broader Impact and Alignment Risks\}.*?)(?=\\subsection\{Implications for Retrieval-Augmented Generation \(RAG\)\})"
match = re.search(broader_impact_regex, text, re.DOTALL)
if match:
    text = text.replace(match.group(1), "")

# Remove the Continuous Learning subsection completely to save space
cont_learn_regex = r"(\\subsection\{Continuous Learning and Zero-Downtime Index Maintenance\}.*?)(?=\\section\{Conclusion\})"
match = re.search(cont_learn_regex, text, re.DOTALL)
if match:
    text = text.replace(match.group(1), "")

# Remove the RAG subsection completely to save space
rag_regex = r"(\\subsection\{Implications for Retrieval-Augmented Generation \(RAG\)\}.*?)(?=\\section\{Conclusion\})"
match = re.search(rag_regex, text, re.DOTALL)
if match:
    text = text.replace(match.group(1), "")

# Merge "Discussion and Broader Impact" section title into Conclusion or just remove the empty section
text = text.replace("\\section{Discussion and Broader Impact}\n\nThe formulation of dense semantic steering as a highly constrained Markov Decision Process operating over a sparse latent dictionary offers a highly sample-efficient alternative to traditional hard-negative fine-tuning. However, transitioning this architecture from a controlled evaluation environment into production systems introduces critical scalability and alignment considerations.\n\n\\subsection{Scalability and Production Indexing}\nWhile our experimental setup explicitly detailed the VRAM efficiency of the PPO agent on a single consumer GPU, real-world deployment necessitates mapping this mathematical framework to a production index. Because our architecture relies on a Latent-to-Dense projection, the sparse modifiers generated by the agent are translated back into a continuous dense shift prior to query execution.\n\nThis structural design allows the steered query to be executed natively against a standard Approximate Nearest Neighbor (ANN) index (e.g., HNSW). Rather than converting the index into discrete posting lists to utilize WAND (Weak AND) or Block-Max WAND dynamic pruning algorithms~\\cite{broder2003}, our agent modifies the query vector in $O(1)$ routing time. By dynamically routing queries in the dense space, our continuous semantic steering avoids the severe latency overheads associated with token-level late-interaction models, while achieving latency profiles structurally analogous to highly-optimized traditional sparse query scheduling~\\cite{macdonald2012}. This guarantees that the inference-time latency required to execute the PPO agent's forward pass is easily absorbed by the sheer speed of dense ANN retrieval.\n\n", "")

# Compress the Conclusion
conc_regex = r"(\\section\{Conclusion\}.*?)(?=\\clearpage)"
match = re.search(conc_regex, text, re.DOTALL)
if match:
    new_conc = "\\section{Conclusion}\nWe introduced a highly efficient Latent-to-Dense framework for correcting semantic drift in dense information retrieval via implicit user feedback. By resolving the continuous-space intractability with a structural bottleneck derived from Sparse Autoencoders, we translated the query perturbation problem into a mathematically tractable Markov Decision Process. Our empirical evaluations demonstrate that a lightweight Proximal Policy Optimization agent can dynamically steer queries away from spurious out-of-domain latent distributions, establishing a robust true zero-shot online correction protocol with minimal computational overhead. This approach provides a scalable pathway toward fully interpretable neural search systems in production environments.\n\n"
    text = text.replace(match.group(1), new_conc)

# Remove the entire "3.1 Continuous Space Intractability" to save space
intractability_regex = r"(\\subsection\{Continuous Space Intractability\}.*?)(?=\\subsection\{Sparse State Projection\})"
match = re.search(intractability_regex, text, re.DOTALL)
if match:
    text = text.replace(match.group(1), "")

with open("main.tex", "w") as f:
    f.write(text)

